postgres:
  image: postgres:9.5
  volumes_from:
    - pg_data

django:
  build: .
  dockerfile: Dockerfile-dev
  user: django
  expose:
    - "5000"
  links:
    - postgres
  command: /gunicorn.sh
  volumes:
    - /trixie/bubbles/static
  env_file: .env-dev

nginx:
  build: ./compose/nginx
  links:
    - django
  volumes:
    - /www/static
  volumes_from:
    - django
  ports:
    - "0.0.0.0:10080:80"

pg_data:
  image: postgres:9.5
  volumes:
    - /data/trixie/postgres:/var/lib/postgresql/data
