FROM python:2.7
ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
ADD ./requirements /requirements

RUN pip install -r /requirements/dev.txt

RUN groupadd -r django && useradd -r -g django django
ADD . /trixie
RUN mkdir -p /trixie/bubbles/static/
RUN chown -R django:django /trixie

ADD ./compose/django/gunicorn.sh /gunicorn.sh
ADD ./compose/django/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh && chown django /entrypoint.sh
RUN chmod +x /gunicorn.sh && chown django /gunicorn.sh


WORKDIR /trixie

ENTRYPOINT ["/entrypoint.sh"]
